// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onArtificialLightChange();
void onWaterpumpChange();

float humidity1;
float humidity2;
float temperature;
int light;
bool artificial_light;
bool waterpump1;
bool waterpump2;

void initProperties(){

  ArduinoCloud.addProperty(humidity1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humidity2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(light, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(artificial_light, READWRITE, ON_CHANGE, onArtificialLightChange);
  ArduinoCloud.addProperty(waterpump1, READWRITE, ON_CHANGE, onWaterpumpChange);
  ArduinoCloud.addProperty(waterpump2, READWRITE, ON_CHANGE, onWaterpumpChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
